apiVersion: apps/v1
kind: Deployment
metadata:
  name: spreadnet-pen-eth-backend
  labels:
    app: spreadnet-pen-eth-backend
    run: spreadnet-pen-eth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spreadnet-pen-eth-backend
  template:
    metadata:
      labels:
        app: spreadnet-pen-eth-backend
        run: spreadnet-pen-eth
    spec:
      containers:
        - name: spreadnet-pen-eth-backend
          imagePullPolicy: Always
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          command: ["python", "./spreadNet_PEN_ETH.py"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: spreadnet-secrets
              mountPath: /var/run/secrets
      volumes:
        - name: config-volume
          configMap:
            name: google-credentials
        - name: spreadnet-secrets
          secret:
            secretName: spreadnet-kubernetes-secrets
