name: Build and Deploy - Develop

on:
  push:
    branches:
    - develop

env:
  PROJECT_ID: gcp-kravata-develop
  GAR_LOCATION: us-central1
  GKE_CLUSTER: develop-cluster
  REPOSITORY: gcp-kravata-develop
  IMAGE: kravata-develop/spreadnet
  ENVIRONMENT: develop

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy - Develop
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY_DEVELOP }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication (https://cloud.google.com/artifact-registry/docs/docker/authentication)
    - name: Docker configuration
      run: |-
        gcloud --quiet auth configure-docker gcr.io

    - name: Install beta components
      run: |-
        gcloud --quiet components install beta

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      run: |-
        gcloud container clusters get-credentials --project $PROJECT_ID --zone $GAR_LOCATION --internal-ip $GKE_CLUSTER

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/kravata-develop/spreadnet:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/kravata-develop/spreadnet:$GITHUB_SHA"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Run Bastion Jump Host
      run: |-
        gcloud beta compute ssh $ENVIRONMENT-bastion --tunnel-through-iap --project $PROJECT_ID --zone us-central1-a -- -fNTL8888:127.0.0.1:8888

    - name: Deploying
      run: |-
        cd kubernetes/overlays/$ENVIRONMENT
        ls -lath ../../../
        ../../../kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/kravata-develop/spreadnet:$GITHUB_SHA
        ../../../kustomize build --reorder none .
        ../../../kustomize build --reorder none . | HTTPS_PROXY=localhost:8888 kubectl apply -f -
    - name: Show Status
      run: |-
        HTTPS_PROXY=localhost:8888 kubectl get all
